version: "3.9"
services:
  app:
    build:
      context: .
    command: >
      sh -c 'python -B manage.py wait_for_db &&
             python -B manage.py migrate &&
             python -B manage.py runserver 0.0.0.0:9000'
    ports:
      - 9000:9000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=testdb
      - DB_USER=beckhong
      - DB_PASS=123
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=beckhong
      - POSTGRES_PASSWORD=123
